name: Run LawScrapper

on:
  schedule:
    - cron: '35 10 * * 0'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      SMTP_PORT: 465
      SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      SMTP_FROM: ${{ secrets.SMTP_FROM }}
      SMTP_TO: ${{ secrets.SMTP_TO }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main script
        run: python main.py
